version: '3.8'

services:
  postgresdb:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=root
      - POSTGRES_DB=python_boilerplate_db
    volumes: 
      - ./database:/docker-entrypoint-initdb.d
    ports: 
      - 5432:5432

  python-app:
    build:
      context: .
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    volumes:
      - "./:/app"
    ports: 
      - 3006:5000
    depends_on:
      - postgresdb